import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import NavBar from "./NavBar";
import Provider from "./auth/Provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <Provider>
          {/* we wrap the whole app in the provider component, which is the hook that provides the session data to the app */}
          <header>
            <NavBar />
          </header>
          <main>
            {/* here we wrap the whole children in a suspense component
            one way to show a loading UI */}
            {/* <Suspense fallback={<div>Loading...</div>}>{children}</Suspense> */}
            {children}
          </main>
        </Provider>
      </body>
    </html>
  );
}
